# DeSO Data Exploration

Explore the structure of DeSO data files before harmonization.

In [1]:
import pandas as pd
import geopandas as gpd
from pathlib import Path

DESO_DIR = Path('/workspace/dbs/deso')
print(f"DeSO directory: {DESO_DIR}")
print(f"Files: {list(DESO_DIR.glob('*'))}")

DeSO directory: /workspace/dbs/deso
Files: [PosixPath('/workspace/dbs/deso/DeSO_2025.gpkg'), PosixPath('/workspace/dbs/deso/deso_birth_background_gender.csv'), PosixPath('/workspace/dbs/deso/deso_income_gender.csv'), PosixPath('/workspace/dbs/deso/deso_passenger_cars_in_traffic.csv')]

## 1. Geometry File

In [2]:
# Load geometry
gdf = gpd.read_file(DESO_DIR / 'DeSO_2025.gpkg')

print(f"Shape: {gdf.shape}")
print(f"\nColumns: {gdf.columns.tolist()}")
print(f"\nDtypes:\n{gdf.dtypes}")
print(f"\nCRS: {gdf.crs}")
print(f"\nFirst 5 rows:")
gdf.head()

ERROR 1: PROJ: proj_create_from_database: Open of /opt/conda/envs/geoenv/share/proj failed

Shape: (6160, 9)

Columns: ['objectid', 'objektidentitet', 'desokod', 'regsokod', 'lanskod', 'kommunkod', 'kommunnamn', 'version', 'geometry']

Dtypes:
objectid              int32
objektidentitet         str
desokod                 str
regsokod                str
lanskod                 str
kommunkod               str
kommunnamn              str
version                 str
geometry           geometry
dtype: object

CRS: EPSG:3006

First 5 rows:

,objectid,objektidentitet,desokod,regsokod,lanskod,kommunkod,kommunnamn,version,geometry
0,1,ad401871-b3ab-444e-bff6-8fdcb442767a,1287B2010,1287R009,12,1287,Trelleborg,2025_v1,"POLYGON ((398220.208 6136028.939, 398131.277 6..."
1,2,90709738-ea97-454d-b135-071a634d5e5e,1287C1080,1287R014,12,1287,Trelleborg,2025_v1,"POLYGON ((385026.453 6138309.345, 385034.006 6..."
2,3,4bae6d9d-7475-4be1-a88e-ca13336cddb0,1287C1060,1287R006,12,1287,Trelleborg,2025_v1,"POLYGON ((384150.992 6138331.011, 384220.768 6..."
3,4,a73b82c2-2cbb-40c6-b137-fd3c0b9c69f1,1287C1040,1287R010,12,1287,Trelleborg,2025_v1,"POLYGON ((383184.933 6138362.314, 383335.536 6..."
4,5,2c30b1ec-91e9-457a-93a2-1a8b6a2778da,1287C1010,1287R004,12,1287,Trelleborg,2025_v1,"POLYGON ((388751.769 6136871.608, 388793.831 6..."

In [3]:
# Check which column contains DeSO codes
print("Sample values from each column:")
for col in gdf.columns:
    if col != 'geometry':
        print(f"\n{col}:")
        print(gdf[col].head(3).tolist())

Sample values from each column:

objectid:
[1, 2, 3]

objektidentitet:
['ad401871-b3ab-444e-bff6-8fdcb442767a', '90709738-ea97-454d-b135-071a634d5e5e', '4bae6d9d-7475-4be1-a88e-ca13336cddb0']

desokod:
['1287B2010', '1287C1080', '1287C1060']

regsokod:
['1287R009', '1287R014', '1287R006']

lanskod:
['12', '12', '12']

kommunkod:
['1287', '1287', '1287']

kommunnamn:
['Trelleborg', 'Trelleborg', 'Trelleborg']

version:
['2025_v1', '2025_v1', '2025_v1']

## 2. Birth Background File

In [4]:
# Load birth background - check both with and without skiprows
print("=== First row (header description) ===")
with open(DESO_DIR / 'deso_birth_background_gender.csv', 'r', encoding='latin1') as f:
    print(f.readline())
    print(f.readline())
    print(f.readline())

print("\n=== Loading with skiprows=1 ===")
df_birth = pd.read_csv(DESO_DIR / 'deso_birth_background_gender.csv', 
                       skiprows=1, encoding='latin1')
print(f"Shape: {df_birth.shape}")
print(f"\nColumns: {df_birth.columns.tolist()}")
print(f"\nFirst 10 rows:")
df_birth.head(10)

=== First row (header description) ===
"Folkmängden per region efter region, födelseregion, kön och år"



"region","födelseregion","kön","2024"


=== Loading with skiprows=1 ===
Shape: (73920, 4)

Columns: ['region', 'födelseregion', 'kön', '2024']

First 10 rows:

      region                        födelseregion      kön  2024
0  0114A0010                              Sverige      män   369
1  0114A0010                              Sverige  kvinnor   359
2  0114A0010                              Sverige   totalt   728
3  0114A0010                  Europa utom Sverige      män    56
4  0114A0010                  Europa utom Sverige  kvinnor    57
5  0114A0010                  Europa utom Sverige   totalt   113
6  0114A0010  övriga världen inkl. uppgift saknas      män    29
7  0114A0010  övriga världen inkl. uppgift saknas  kvinnor    22
8  0114A0010  övriga världen inkl. uppgift saknas   totalt    51
9  0114A0010                               totalt      män   454

In [5]:
# Check unique values
print("Unique values in column 1 (birth region):")
print(df_birth.iloc[:, 1].unique())

print("\nUnique values in column 2 (gender):")
print(df_birth.iloc[:, 2].unique())

print("\nSample DeSO codes from column 0:")
print(df_birth.iloc[:, 0].head(10).tolist())

Unique values in column 1 (birth region):
<ArrowStringArray>
[                            'Sverige',                 'Europa utom Sverige',
 'övriga världen inkl. uppgift saknas',                              'totalt']
Length: 4, dtype: str

Unique values in column 2 (gender):
<ArrowStringArray>
['män', 'kvinnor', 'totalt']
Length: 3, dtype: str

Sample DeSO codes from column 0:
['0114A0010', '0114A0010', '0114A0010', '0114A0010', '0114A0010', '0114A0010', '0114A0010', '0114A0010', '0114A0010', '0114A0010']

In [6]:
# Filter to 'totalt' gender
df_birth.columns = ['region', 'birth_region', 'gender', 'count']
df_birth_total = df_birth[df_birth['gender'] == 'totalt'].copy()
df_birth_total = df_birth_total[df_birth_total['birth_region'] != 'totalt'].copy()

print(f"After filtering to 'totalt' gender (excl. 'totalt' birth region): {len(df_birth_total)} rows")
print(f"\nUnique birth regions: {df_birth_total['birth_region'].unique()}")
print(f"\nSample:")
df_birth_total.head(10)

After filtering to 'totalt' gender (excl. 'totalt' birth region): 18480 rows

Unique birth regions: <ArrowStringArray>
['Sverige', 'Europa utom Sverige', 'övriga världen inkl. uppgift saknas']
Length: 3, dtype: str

Sample:

       region                         birth_region  gender  count
2   0114A0010                              Sverige  totalt    728
5   0114A0010                  Europa utom Sverige  totalt    113
8   0114A0010  övriga världen inkl. uppgift saknas  totalt     51
14  0114C1010                              Sverige  totalt   1247
17  0114C1010                  Europa utom Sverige  totalt    150
20  0114C1010  övriga världen inkl. uppgift saknas  totalt    173
26  0114C1020                              Sverige  totalt   1272
29  0114C1020                  Europa utom Sverige  totalt    133
32  0114C1020  övriga världen inkl. uppgift saknas  totalt    202
38  0114C1030                              Sverige  totalt   1813

In [7]:
# Pivot
birth_wide = df_birth_total.pivot(index='region', columns='birth_region', values='count').reset_index()
print(f"Pivoted shape: {birth_wide.shape}")
print(f"\nColumns: {birth_wide.columns.tolist()}")
birth_wide.head()

Pivoted shape: (6160, 4)

Columns: ['region', 'Europa utom Sverige', 'Sverige', 'övriga världen inkl. uppgift saknas']

birth_region,region,Europa utom Sverige,Sverige,övriga världen inkl. uppgift saknas
0,0114A0010,113,728,51
1,0114C1010,150,1247,173
2,0114C1020,133,1272,202
3,0114C1030,206,1813,264
4,0114C1040,449,1372,627

## 3. Income File

In [8]:
print("=== First row (header description) ===")
with open(DESO_DIR / 'deso_income_gender.csv', 'r', encoding='latin1') as f:
    print(f.readline())
    print(f.readline())

print("\n=== Loading with skiprows=1 ===")
df_income = pd.read_csv(DESO_DIR / 'deso_income_gender.csv', 
                        skiprows=1, encoding='latin1')
print(f"Shape: {df_income.shape}")
print(f"\nColumns: {df_income.columns.tolist()}")
print(f"\nFirst 5 rows:")
df_income.head()

=== First row (header description) ===
"Andel av befolkningen i inkomstklass efter region, inkomstslag, kön, tabellinnehåll och år"




=== Loading with skiprows=1 ===
Shape: (18480, 10)

Columns: ['region', 'inkomstslag', 'kön', 'Kvartil 1, andel personer, procent 2024', 'Kvartil 2, andel personer, procent 2024', 'Kvartil 3, andel personer, procent 2024', 'Kvartil 4, andel personer, procent 2024', 'Medianvärde, tkr 2024', 'Medelvärde, tkr 2024', 'Antal personer totalt 2024']

First 5 rows:

,region,inkomstslag,kön,"Kvartil 1, andel personer, procent 2024","Kvartil 2, andel personer, procent 2024","Kvartil 3, andel personer, procent 2024","Kvartil 4, andel personer, procent 2024","Medianvärde, tkr 2024","Medelvärde, tkr 2024",Antal personer totalt 2024
0,0114A0010,sammanräknad förvärvsinkomst,män,20,19,17,44,471.4,531.1,353
1,0114A0010,sammanräknad förvärvsinkomst,kvinnor,23,29,19,30,345.1,430.9,333
2,0114A0010,sammanräknad förvärvsinkomst,totalt,21,24,18,37,400.8,482.5,682
3,0114C1010,sammanräknad förvärvsinkomst,män,16,13,22,49,506.6,569.9,588
4,0114C1010,sammanräknad förvärvsinkomst,kvinnor,20,21,24,35,412.8,448.5,577

In [9]:
# Check unique values
print("Unique income types (column 1):")
print(df_income.iloc[:, 1].unique())

print("\nUnique genders (column 2):")
print(df_income.iloc[:, 2].unique())

Unique income types (column 1):
<ArrowStringArray>
['sammanräknad förvärvsinkomst']
Length: 1, dtype: str

Unique genders (column 2):
<ArrowStringArray>
['män', 'kvinnor', 'totalt']
Length: 3, dtype: str

In [10]:
# Filter to 'sammanräknad' and 'totalt'
df_income.columns = ['region', 'income_type', 'gender', 'q1_pct', 'q2_pct', 
                     'q3_pct', 'q4_pct', 'median_tkr', 'mean_tkr', 'n_persons']

df_income_filt = df_income[
    (df_income['income_type'].str.contains('sammanr', na=False)) &
    (df_income['gender'] == 'totalt')
].copy()

print(f"After filtering: {len(df_income_filt)} rows")
print(f"\nSample:")
df_income_filt.head()

After filtering: 6160 rows

Sample:

,region,income_type,gender,q1_pct,q2_pct,q3_pct,q4_pct,median_tkr,mean_tkr,n_persons
2,0114A0010,sammanräknad förvärvsinkomst,totalt,21,24,18,37,400.8,482.5,682
5,0114C1010,sammanräknad förvärvsinkomst,totalt,18,17,23,42,455.8,509.8,1167
8,0114C1020,sammanräknad förvärvsinkomst,totalt,17,22,22,39,446.9,481.4,1137
11,0114C1030,sammanräknad förvärvsinkomst,totalt,18,21,24,37,428.4,467.7,1723
14,0114C1040,sammanräknad förvärvsinkomst,totalt,28,29,26,17,328.0,342.9,1835

## 4. Cars File

In [11]:
print("=== First row (header description) ===")
with open(DESO_DIR / 'deso_passenger_cars_in_traffic.csv', 'r', encoding='latin1') as f:
    print(f.readline())
    print(f.readline())

print("\n=== Loading with skiprows=1 ===")
df_cars = pd.read_csv(DESO_DIR / 'deso_passenger_cars_in_traffic.csv',
                      skiprows=1, encoding='latin1')
print(f"Shape: {df_cars.shape}")
print(f"\nColumns: {df_cars.columns.tolist()}")
print(f"\nFirst 10 rows:")
df_cars.head(10)

=== First row (header description) ===
"Personbilar i trafik registrerade på folkbokförda personer 31 december, antal efter region, status och år"




=== Loading with skiprows=1 ===
Shape: (6160, 3)

Columns: ['region', 'status', '2024']

First 10 rows:

      region    status  2024
0  0114A0010  i trafik   430
1  0114C1010  i trafik   726
2  0114C1020  i trafik   741
3  0114C1030  i trafik  1018
4  0114C1040  i trafik   770
5  0114C1050  i trafik   875
6  0114C1061  i trafik   680
7  0114C1062  i trafik   448
8  0114C1070  i trafik   751
9  0114C1080  i trafik   693

## 5. Check Join Keys

In [12]:
# Compare DeSO codes across files
print("DeSO code samples from each file:")
print("\nGeometry file:")
if 'deso' in gdf.columns:
    print(f"  Column: 'deso'")
    print(f"  Sample: {gdf['deso'].head(5).tolist()}")
elif 'DeSO' in gdf.columns:
    print(f"  Column: 'DeSO'")
    print(f"  Sample: {gdf['DeSO'].head(5).tolist()}")
else:
    print(f"  Available columns: {[c for c in gdf.columns if c != 'geometry']}")
    for col in gdf.columns:
        if col != 'geometry':
            print(f"  {col}: {gdf[col].head(3).tolist()}")

print("\nBirth file (region column):")
print(f"  Sample: {birth_wide['region'].head(5).tolist()}")

print("\nIncome file (region column):")
print(f"  Sample: {df_income_filt['region'].head(5).tolist()}")

print("\nCars file:")
df_cars.columns = ['region', 'status', 'count']
print(f"  Sample: {df_cars['region'].head(5).tolist()}")

DeSO code samples from each file:

Geometry file:
  Available columns: ['objectid', 'objektidentitet', 'desokod', 'regsokod', 'lanskod', 'kommunkod', 'kommunnamn', 'version']
  objectid: [1, 2, 3]
  objektidentitet: ['ad401871-b3ab-444e-bff6-8fdcb442767a', '90709738-ea97-454d-b135-071a634d5e5e', '4bae6d9d-7475-4be1-a88e-ca13336cddb0']
  desokod: ['1287B2010', '1287C1080', '1287C1060']
  regsokod: ['1287R009', '1287R014', '1287R006']
  lanskod: ['12', '12', '12']
  kommunkod: ['1287', '1287', '1287']
  kommunnamn: ['Trelleborg', 'Trelleborg', 'Trelleborg']
  version: ['2025_v1', '2025_v1', '2025_v1']

Birth file (region column):
  Sample: ['0114A0010', '0114C1010', '0114C1020', '0114C1030', '0114C1040']

Income file (region column):
  Sample: ['0114A0010', '0114C1010', '0114C1020', '0114C1030', '0114C1040']

Cars file:
  Sample: ['0114A0010', '0114C1010', '0114C1020', '0114C1030', '0114C1040']

In [14]:
# Check for matches
print("Checking overlap:")

# Find the DeSO code column in geometry
geo_deso_col = None
for col in ['deso', 'DeSO', 'desokod']:
    if col in gdf.columns:
        geo_deso_col = col
        break

if geo_deso_col:
    geo_codes = set(gdf[geo_deso_col])
    birth_codes = set(birth_wide['region'])
    income_codes = set(df_income_filt['region'])
    cars_codes = set(df_cars['region'])
    
    print(f"\nGeometry: {len(geo_codes):,} DeSO codes")
    print(f"Birth: {len(birth_codes):,} DeSO codes")
    print(f"Income: {len(income_codes):,} DeSO codes")
    print(f"Cars: {len(cars_codes):,} DeSO codes")
    
    print(f"\nOverlap with geometry:")
    print(f"  Birth: {len(geo_codes & birth_codes):,} / {len(birth_codes):,} ({len(geo_codes & birth_codes)/len(birth_codes)*100:.1f}%)")
    print(f"  Income: {len(geo_codes & income_codes):,} / {len(income_codes):,} ({len(geo_codes & income_codes)/len(income_codes)*100:.1f}%)")
    print(f"  Cars: {len(geo_codes & cars_codes):,} / {len(cars_codes):,} ({len(geo_codes & cars_codes)/len(cars_codes)*100:.1f}%)")
    
    # Show sample mismatches
    birth_only = birth_codes - geo_codes
    if birth_only:
        print(f"\nSample codes in Birth but not Geometry: {list(birth_only)[:5]}")
    
    geo_only = geo_codes - birth_codes
    if geo_only:
        print(f"Sample codes in Geometry but not Birth: {list(geo_only)[:5]}")
else:
    print("Could not find DeSO code column in geometry file!")
    print(f"Available columns: {gdf.columns.tolist()}")

Checking overlap:

Geometry: 6,160 DeSO codes
Birth: 6,160 DeSO codes
Income: 6,160 DeSO codes
Cars: 6,160 DeSO codes

Overlap with geometry:
  Birth: 6,160 / 6,160 (100.0%)
  Income: 6,160 / 6,160 (100.0%)
  Cars: 6,160 / 6,160 (100.0%)

## 6. Test Join

In [15]:
# Try joining
if geo_deso_col:
    # Rename for consistency
    gdf_test = gdf.rename(columns={geo_deso_col: 'deso_kod'})
    birth_test = birth_wide.rename(columns={'region': 'deso_kod'})
    
    # Test join
    result = gdf_test.merge(birth_test, on='deso_kod', how='left')
    
    print(f"Join result shape: {result.shape}")
    print(f"\nColumns: {result.columns.tolist()}")
    print(f"\nFirst 5 rows:")
    display(result.head())
    
    print(f"\nMissing data after join:")
    for col in result.columns:
        if col not in ['deso_kod', 'geometry']:
            n_missing = result[col].isna().sum()
            print(f"  {col}: {n_missing:,} missing ({n_missing/len(result)*100:.1f}%)")

Join result shape: (6160, 12)

Columns: ['objectid', 'objektidentitet', 'deso_kod', 'regsokod', 'lanskod', 'kommunkod', 'kommunnamn', 'version', 'geometry', 'Europa utom Sverige', 'Sverige', 'övriga världen inkl. uppgift saknas']

First 5 rows:

,objectid,objektidentitet,deso_kod,regsokod,lanskod,kommunkod,kommunnamn,version,geometry,Europa utom Sverige,Sverige,övriga världen inkl. uppgift saknas
0,1,ad401871-b3ab-444e-bff6-8fdcb442767a,1287B2010,1287R009,12,1287,Trelleborg,2025_v1,"POLYGON ((398220.208 6136028.939, 398131.277 6...",123,1338,38
1,2,90709738-ea97-454d-b135-071a634d5e5e,1287C1080,1287R014,12,1287,Trelleborg,2025_v1,"POLYGON ((385026.453 6138309.345, 385034.006 6...",474,1192,272
2,3,4bae6d9d-7475-4be1-a88e-ca13336cddb0,1287C1060,1287R006,12,1287,Trelleborg,2025_v1,"POLYGON ((384150.992 6138331.011, 384220.768 6...",458,1641,265
3,4,a73b82c2-2cbb-40c6-b137-fd3c0b9c69f1,1287C1040,1287R010,12,1287,Trelleborg,2025_v1,"POLYGON ((383184.933 6138362.314, 383335.536 6...",180,1112,168
4,5,2c30b1ec-91e9-457a-93a2-1a8b6a2778da,1287C1010,1287R004,12,1287,Trelleborg,2025_v1,"POLYGON ((388751.769 6136871.608, 388793.831 6...",137,2016,45

Missing data after join:
  objectid: 0 missing (0.0%)
  objektidentitet: 0 missing (0.0%)
  regsokod: 0 missing (0.0%)
  lanskod: 0 missing (0.0%)
  kommunkod: 0 missing (0.0%)
  kommunnamn: 0 missing (0.0%)
  version: 0 missing (0.0%)
  Europa utom Sverige: 0 missing (0.0%)
  Sverige: 0 missing (0.0%)
  övriga världen inkl. uppgift saknas: 0 missing (0.0%)